#!/usr/bin/env bash
# Boot Profiles stage A (§8.2c) — the WITNESS-PREFIX CENSUS generator.
#
# The substrate lane's anti-hollow CORE is a NEGATIVE assertion: on a substrate
# boot NO agent-organ witness family may appear (organs proven NOT to have run —
# what distinguishes a profile from a render filter). That ABSENT list must NOT
# be hand-maintained (a hand list drifts — the V1 draft missed `mem:`/
# `conduct-step:`/`cost:`). Instead it is DERIVED here and committed to
# `scripts/witness-census.txt`; the substrate lane asserts against the committed
# copy, and CI RE-RUNS this generator and diffs it against the commit — so a
# future organ's new witness prefix cannot silently escape the inversion (it
# lands in the census automatically unless it is a declared CORE witness).
#
# Mechanism: extract every `word:` witness prefix EMITTED over serial in
# kernel/src/main.rs, then SUBTRACT the CORE allowlist below (the micro-VMM /
# self-test witnesses that legitimately appear on a substrate boot). The
# remainder is the agent-organ census. A handful of non-`word:` TOKENS that a
# substrate boot must also never carry (the M38 conductor's decision tokens) are
# appended verbatim.
#
# Usage:  scripts/gen-witness-census.sh          # print the census to stdout
#         scripts/gen-witness-census.sh --check  # diff vs the committed file
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAIN="${REPO_ROOT}/kernel/src/main.rs"
COMMITTED="${REPO_ROOT}/scripts/witness-census.txt"

# CORE witnesses — emitted by the profile-scoped micro-VMM core + the M0..M11
# self-tests + L2/EL2 + the substrate integrity primitive (khash) + the Yuva-ABI
# self-check. These legitimately appear on a SUBSTRATE boot and are NOT organ
# evidence. Everything else that is emitted as a `word:` witness is an organ.
CORE_ALLOW='mmu-test alloc-test frame-test heap-test timer-test preempt-test
ctx-test trap-test user-test addrspace-test addrspace caps trap preempt sched
timer m9 m12 agent ipc blocks unmap virtio persist khash abi abi-conformance
boot tb-boot panic leak vmx el2 smmu guest guestboot guestchain guestprobe
guestlog model'

# Every `word:` prefix emitted over serial (single-line and multi-line forms).
emitted_prefixes() {
  grep -oE '"[[:space:]]*[a-z][a-z0-9-]*: ' "$MAIN" \
    | grep -oE '[a-z][a-z0-9-]*:' | sort -u
}

gen() {
  local allow
  allow="$(printf '%s\n' $CORE_ALLOW | sed 's/$/:/' | sort -u)"
  echo "# Boot Profiles §8.2c — GENERATED by scripts/gen-witness-census.sh; do not hand-edit."
  echo "# Agent-organ witness prefixes that MUST be ABSENT on a substrate boot."
  emitted_prefixes | grep -vxF "$allow" | grep -vxf <(printf '%s\n' "$allow")
  echo "# Non-prefix decision tokens the substrate boot must also never carry:"
  echo "verdict=ACCEPT"
  echo "turns="
  echo "backend=MOCK-DETERMINISTIC"
}

case "${1:-}" in
  --check)
    if ! diff -u "$COMMITTED" <(gen); then
      echo ">> FAIL: witness census drift — scripts/witness-census.txt is stale." >&2
      echo ">>   regenerate: scripts/gen-witness-census.sh > scripts/witness-census.txt" >&2
      exit 1
    fi
    echo ">> witness census up to date."
    ;;
  *)
    gen
    ;;
esac
